In [1]:
from sqlalchemy import create_engine
import pandas as pd
from config import db_password

In [2]:
# Files to load
UserInfo_data_to_load = "Resources/CarDetailsV3_UserInfo.csv"
EngineInfo_data_to_load = "Resources/CarDetailsV3_CarEngineInfo.csv"
CarYear_data_to_load = "Resources/CarDetailsV3_CarYear.csv"

In [3]:
# Read the data files and store it in a pandas DataFrame.
UserInfo_df = pd.read_csv(UserInfo_data_to_load)
UserInfo_df.head(10)

                                   name seller_type transmission         owner
0                Maruti Swift Dzire VDI  Individual       Manual   First Owner
1          Skoda Rapid 1.5 TDI Ambition  Individual       Manual  Second Owner
2              Honda City 2017-2020 EXi  Individual       Manual   Third Owner
3             Hyundai i20 Sportz Diesel  Individual       Manual   First Owner
4                Maruti Swift VXI BSIII  Individual       Manual   First Owner
5         Hyundai Xcent 1.2 VTVT E Plus  Individual       Manual   First Owner
6          Maruti Wagon R LXI DUO BSIII  Individual       Manual   First Owner
7                    Maruti 800 DX BSII  Individual       Manual  Second Owner
8                      Toyota Etios VXD  Individual       Manual   First Owner
9  Ford Figo Diesel Celebration Edition  Individual       Manual   First Owner

In [4]:
EngineInfo_df = pd.read_csv(EngineInfo_data_to_load)
EngineInfo_df.head(10)

,name,selling_price,km_driven,fuel,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,450000,145500,Diesel,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0
1,Skoda Rapid 1.5 TDI Ambition,370000,120000,Diesel,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0
2,Honda City 2017-2020 EXi,158000,140000,Petrol,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0
3,Hyundai i20 Sportz Diesel,225000,127000,Diesel,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0
4,Maruti Swift VXI BSIII,130000,120000,Petrol,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0
5,Hyundai Xcent 1.2 VTVT E Plus,440000,45000,Petrol,20.14 kmpl,1197 CC,81.86 bhp,113.75nm@ 4000rpm,5.0
6,Maruti Wagon R LXI DUO BSIII,96000,175000,LPG,17.3 km/kg,1061 CC,57.5 bhp,"7.8@ 4,500(kgm@ rpm)",5.0
7,Maruti 800 DX BSII,45000,5000,Petrol,16.1 kmpl,796 CC,37 bhp,59Nm@ 2500rpm,4.0
8,Toyota Etios VXD,350000,90000,Diesel,23.59 kmpl,1364 CC,67.1 bhp,170Nm@ 1800-2400rpm,5.0
9,Ford Figo Diesel Celebration Edition,200000,169000,Diesel,20.0 kmpl,1399 CC,68.1 bhp,160Nm@ 2000rpm,5.0

In [5]:
CarYear_df = pd.read_csv(CarYear_data_to_load)
CarYear_df.head(10)

                                   name  year
0                Maruti Swift Dzire VDI  2014
1          Skoda Rapid 1.5 TDI Ambition  2014
2              Honda City 2017-2020 EXi  2006
3             Hyundai i20 Sportz Diesel  2010
4                Maruti Swift VXI BSIII  2007
5         Hyundai Xcent 1.2 VTVT E Plus  2017
6          Maruti Wagon R LXI DUO BSIII  2007
7                    Maruti 800 DX BSII  2001
8                      Toyota Etios VXD  2011
9  Ford Figo Diesel Celebration Edition  2013

In [6]:
# Create the connection string using the password from the config.py file
db_string = f"postgres://postgres:{db_password}@127.0.0.1:5432/Car_Dekho_Prediction"

In [7]:
# Create the database engine
engine = create_engine(db_string)

In [8]:
# Import the CarYear file to PostGreSQL
CarYear_df.to_sql(name='CarYear', con=engine)

In [9]:
# Import the EngineInfo file to PostGreSQL
EngineInfo_df.to_sql(name='CarEngineInfo', con=engine)

In [10]:
# Import the UserInfo file to PostGreSQL
UserInfo_df.to_sql(name='UserInfo', con=engine)